version: "3"

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWOR:
      DATABASE_NAME:
      API_KEY_GOOGLE_FCM:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
